export const ACTIONS=["Open","TakeOff","Cut","Put","Finish"] as const;
export const INGREDIENTS=["bread","ham","tomato","cheese","mayonnaise","cabbage"] as const;
export const AMOUNTS=["L","M","S"] as const;
type Action=(typeof ACTIONS)[number];type Ingredient=(typeof INGREDIENTS)[number];type Amount=(typeof AMOUNTS)[number];
export interface SandwichAction{action:Action;targetIngredient:Ingredient|null;amount:Amount|null;rawCommandPart:string}export interface SandwichResponse{actions:SandwichAction[]}
export const sandwichResponseSchema={type:"object",additionalProperties:false,required:["actions"],properties:{actions:{type:"array",maxItems:10,items:{type:"object",additionalProperties:false,required:["action","targetIngredient","amount","rawCommandPart"],properties:{action:{type:"string",enum:ACTIONS},targetIngredient:{type:["string","null"],enum:[...INGREDIENTS,null]},amount:{type:["string","null"],enum:[...AMOUNTS,null]},rawCommandPart:{type:"string"}}}}}} as const;
const states:Record<Ingredient,ReadonlySet<string>>={
 bread:new Set(["BREAD_BAG_CLOSED_LOAF","L_CUT_BREAD_BAG_CLOSED_LOAF","M_CUT_BREAD_BAG_CLOSED_LOAF","S_CUT_BREAD_BAG_CLOSED_LOAF","BREAD_BAG_OPENED_LOAF","L_CUT_BREAD_BAG_OPENED_LOAF","M_CUT_BREAD_BAG_OPENED_LOAF","S_CUT_BREAD_BAG_OPENED_LOAF","BREAD_LOAF","L_CUT_BREAD_LOAF","M_CUT_BREAD_LOAF","S_CUT_BREAD_LOAF"]),
 ham:new Set(["HAM_PACK_CLOSED_STACK","HAM_PACK_OPENED_STACK","L_CUT_HAM_PACK_CLOSED_STACK","M_CUT_HAM_PACK_CLOSED_STACK","S_CUT_HAM_PACK_CLOSED_STACK","L_CUT_HAM_PACK_OPENED_STACK","M_CUT_HAM_PACK_OPENED_STACK","S_CUT_HAM_PACK_OPENED_STACK","S_TAKEOFF_HAM_SLICE","M_TAKEOFF_HAM_SLICE","L_TAKEOFF_HAM_SLICE"]),
 tomato:new Set(["TOMATO_SLICE_STACK","S_TAKEOFF_TOMATO_SLICE","M_TAKEOFF_TOMATO_SLICE","L_TAKEOFF_TOMATO_SLICE"]),
 cheese:new Set(["CHEESE_PACK_CLOSED_STACK","CHEESE_PACK_OPENED_STACK","L_CUT_CHEESE_PACK_CLOSED_STACK","M_CUT_CHEESE_PACK_CLOSED_STACK","S_CUT_CHEESE_PACK_CLOSED_STACK","L_CUT_CHEESE_PACK_OPENED_STACK","M_CUT_CHEESE_PACK_OPENED_STACK","S_CUT_CHEESE_PACK_OPENED_STACK","S_TAKEOFF_CHEESE_SLICE_WRAPPED","M_TAKEOFF_CHEESE_SLICE_WRAPPED","L_TAKEOFF_CHEESE_SLICE_WRAPPED","S_OPENED_CHEESE_SLICE","M_OPENED_CHEESE_SLICE","L_OPENED_CHEESE_SLICE"]),
 mayonnaise:new Set(["MAYO_BOTTLE_CLOSED","MAYO_TAKEOFF_FAILED_CLOSED","MAYO_BOTTLE_OPENED","S_TAKEOFF_MAYO","M_TAKEOFF_MAYO","L_TAKEOFF_MAYO"]),
 cabbage:new Set(["CABBAGE_PIECE","L_CUT_CABBAGE_PIECE","M_CUT_CABBAGE_PIECE","S_CUT_CABBAGE_PIECE"])};
const record=(v:unknown):v is Record<string,unknown>=>typeof v==="object"&&v!==null&&!Array.isArray(v);
export function validateRequestBody(v:unknown):{command:string;currentStates:Record<Ingredient,string>}|null{if(!record(v)||typeof v.command!=="string"||!record(v.currentStates))return null;const command=v.command.trim();if(command.length<1||command.length>200||Object.keys(v.currentStates).length!==6)return null;const currentStates={} as Record<Ingredient,string>;for(const i of INGREDIENTS){const id=v.currentStates[i];if(typeof id!=="string"||!states[i].has(id))return null;currentStates[i]=id;}return{command,currentStates};}
export function validateModelResponse(v:unknown):v is SandwichResponse{if(!record(v)||Object.keys(v).length!==1||!Array.isArray(v.actions)||v.actions.length>10)return false;return v.actions.every(x=>{if(!record(x)||Object.keys(x).length!==4||!ACTIONS.includes(x.action as Action)||typeof x.rawCommandPart!=="string")return false;const a=x.action as Action;if(!(x.targetIngredient===null||INGREDIENTS.includes(x.targetIngredient as Ingredient))||!(x.amount===null||AMOUNTS.includes(x.amount as Amount)))return false;if(a==="Finish")return x.targetIngredient===null&&x.amount===null;if(x.targetIngredient===null)return false;return a==="Cut"||a==="TakeOff"?x.amount!==null:x.amount===null;});}
